export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ASYNC_MOUNT_INGREDIENTS = "ASYNC_MOUNT_INGREDIENTS";
export const MOUNT_INGREDIENTS_FAIL = "MOUNT_INGREDIENTS_FAIL";

export const ASYNC_MOUNT_ORDERS = "ASYNC_MOUNT_ORDERS";
export const MOUNT_ORDERS_FAIL = "MOUNT_ORDERS_FAIL";

export const SUBMIT_CONTACT_DATA = "SUBMIT_CONTACT_DATA";
export const SUBMIT_CONTACT_DATA_START = "SUBMIT_CONTACT_DATA_START";
export const SUBMIT_CONTANT_DATA_FAIL = "SUBMIT_CONTANT_DATA_FAIL";
export const ASYNC_SUBMIT_CONTACT_DATA = "ASYNC_SUBMIT_CONTACT_DATA";
